name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        cd rust/mdtesting
        rustup default nightly
        cargo build --verbose
    - name: Run tests
      run: |
        cd rust/mdtesting
        rustup default nightly
        cargo test --verbose